from sqlmodel import SQLModel, Field
from sqlalchemy import Column, Date, DateTime, Double, Integer, BigInteger, Text, String
from datetime import date, datetime
from typing import Optional
from decimal import Decimal

class Motor(SQLModel, table=True):
    __tablename__ = "motor"
    riqi: date = Field(sa_column=Column("日期", Date))
    shengchan_renwu_danhao: str = Field(sa_column=Column("生产任务单号", Text))
    gongxu: str = Field(sa_column=Column("工序", Text))
    biaozhun_renli: int = Field(sa_column=Column("标准人力", Integer))
    biaozhun_gongshi: int = Field(sa_column=Column("标准工时", Integer))
    toure_renli: Decimal = Field(sa_column=Column("投入人力", Double(asdecimal=True)))
    toure_gongshi: Decimal = Field(sa_column=Column("投入工时", Double(asdecimal=True)))
    dangtian_chuqin_shichang_per_person: Decimal = Field(sa_column=Column("当天出勤时长", Double(asdecimal=True)))
    zhengban_gongshi: Decimal = Field(sa_column=Column("正班工时", Double(asdecimal=True)))
    jiaban_gongshi: Decimal = Field(sa_column=Column("加班工时", Double(asdecimal=True)))
    shiji_chaneng: int = Field(sa_column=Column("实际产能", Integer))
    biaozhun_channeng: int = Field(sa_column=Column("标准产量", Integer))
    jihuashu: int = Field(sa_column=Column("计划数", Integer))
    dachenglv: str = Field(sa_column=Column("达成率", Text))
    xiaolv: str = Field(sa_column=Column("效率", Text))
    buliangshu: int = Field(sa_column=Column("不良数", Integer))
    bulianglv: Decimal = Field(sa_column=Column("不良率", Double(asdecimal=True)))
    buliang_mingxi: str = Field(sa_column=Column("不良明细", Text))
    beizhu: Optional[str] = Field(default=None, sa_column=Column("备注", Text, nullable=True))

class MotorExceptionWks(SQLModel, table=True):
    __tablename__ = "motor_exception_wks"
    riqi: datetime = Field(sa_column=Column("日期", DateTime))
    zuoye_miaoshu: str = Field(sa_column=Column("作业描述", Text))
    renyuan: int = Field(sa_column=Column("人员", BigInteger))
    heji_gongshi: Decimal = Field(sa_column=Column("合计工时", Double(asdecimal=True)))
    yichang_fenlei: str = Field(sa_column=Column("异常分类", Text))
    zeren_bumen: str = Field(sa_column=Column("责任部门", Text))
    beizhu: Optional[str] = Field(default=None, sa_column=Column("备注", Text, nullable=True))

class MotorScrap(SQLModel, table=True):
    __tablename__ = "motor_scrap"
    kucun_fangxiang: str = Field(sa_column=Column("库存方向", Text))
    danju_leixing: str = Field(sa_column=Column("单据类型", Text))
    danju_zhuangtai: str = Field(sa_column=Column("单据状态", Text))
    danju_bianhao: str = Field(sa_column=Column("单据编号", Text))
    gongdan_bianhao: str = Field(sa_column=Column("工单编号", Text))
    chanpin_bianma: str = Field(sa_column=Column("产品编码", Text))
    chanpin_mingcheng: str = Field(sa_column=Column("产品名称", Text))
    gongdan_leixing: str = Field(sa_column=Column("工单类型", Text))
    chanpin_cunhuo_leibie: str = Field(sa_column=Column("产品存货类别", Text))
    chanpin_xilie: str = Field(sa_column=Column("产品系列", Text))
    shougong_yuanyin: str = Field(sa_column=Column("手工原因", Text))
    baofei_yuanyin_dalei: str = Field(sa_column=Column("报废原因大类", Text))
    riqi: date = Field(sa_column=Column("日期", Date))
    lingliao_bumen: str = Field(sa_column=Column("领料部门", Text))
    bumen: str = Field(sa_column=Column("部门", Text))
    wuliao_bianma: str = Field(sa_column=Column("物料编码", Text))
    wuliao_mingcheng: str = Field(sa_column=Column("物料名称", Text))
    guige_xinghao: str = Field(sa_column=Column("规格型号", Text))
    chanpin_pinlei: str = Field(sa_column=Column("产品品类", Text))
    wuliao_leibie: str = Field(sa_column=Column("物料类别", Text))
    danwei: str = Field(sa_column=Column("单位", Text))
    shifa_shuliang: Decimal = Field(sa_column=Column("实发数量", Double(asdecimal=True)))
    fahuo_cangku: str = Field(sa_column=Column("发货仓库", Text))

class MotorStorage(SQLModel, table=True):
    __tablename__ = "motor_storage"
    laiyuan_danju_leixing: str = Field(sa_column=Column("来源单据类型", Text))
    laiyuan_danju_bianhao: str = Field(sa_column=Column("来源单据编号", Text))
    danju_leixing: str = Field(sa_column=Column("单据类型", Text))
    yewu_riqi: date = Field(sa_column=Column("业务日期", Date))
    zhordu: Decimal = Field(sa_column=Column("周度", Double(asdecimal=True)))
    chanpin_bianma: str = Field(sa_column=Column("产品编码", Text))
    chanpin_mingcheng: str = Field(sa_column=Column("产品名称", Text))
    guige_xinghao: str = Field(sa_column=Column("规格型号", Text))
    chanpin_leixing: str = Field(sa_column=Column("产品类型", Text))
    xilie_fenlei: str = Field(sa_column=Column("系列分类", Text))
    wuliao_fenzu: str = Field(sa_column=Column("物料分组", Text))
    cunhuo_leibie: str = Field(sa_column=Column("存货类别", Text))
    shengchan_chejian: str = Field(sa_column=Column("生产车间", Text))
    jiben_danwei: str = Field(sa_column=Column("基本单位", Text))
    shuliang: int = Field(sa_column=Column("数量", BigInteger))
    danjia: Decimal = Field(sa_column=Column("单价", Double(asdecimal=True)))
    jine: Decimal = Field(sa_column=Column("金额", Double(asdecimal=True)))
    cangku: str = Field(sa_column=Column("仓库", Text))
    shengchan_leixing: str = Field(sa_column=Column("生产类型", Text))
    huozhu: str = Field(sa_column=Column("货主", Text))
    gongdan_leixing: str = Field(sa_column=Column("工单类型", Text))
    gongdan_bianhao: str = Field(sa_column=Column("工单编号", Text))

class ShapeExceptionWks(SQLModel, table=True):
    __tablename__ = "shape_exception_wks"
    riqi: date = Field(sa_column=Column("日期", Date))
    zeren_bumen: str = Field(sa_column=Column("责任部门", Text))
    fenlei: str = Field(sa_column=Column("分类", Text))
    zong_gongshi_h: Decimal = Field(sa_column=Column("总工时(H)", Double(asdecimal=True)))
    zong_chuqin_gongshi_h: Decimal = Field(sa_column=Column("总出勤工时", Double(asdecimal=True)))

class ShapeProduct(SQLModel, table=True):
    __tablename__ = "shape_product"
    riqi: date = Field(sa_column=Column("日期", Date))
    banci: str = Field(sa_column=Column("班次", Text))
    pinming: str = Field(sa_column=Column("品名", Text))
    shengchan_dingdanhao: str = Field(sa_column=Column("生产订单号", Text))
    chanpin_bianma: str = Field(sa_column=Column("产品编码", Text))
    xianbie: str = Field(sa_column=Column("线别", Text))
    pinlei: str = Field(sa_column=Column("品类", Text))
    gangwei: str = Field(sa_column=Column("岗位", Text))
    mingxi_gongduan: str = Field(sa_column=Column("明细工段", Text))
    zuoye_neirong: str = Field(sa_column=Column("作业内容", Text))
    biaopei_renli: Decimal = Field(sa_column=Column("标配人力", Double(asdecimal=True)))
    xueshu: int = Field(sa_column=Column("穴数", BigInteger))
    zhouqi: Decimal = Field(sa_column=Column("周期", Double(asdecimal=True)))
    biaozhun_gongshi: Decimal = Field(sa_column=Column("标准工时", Double(asdecimal=True)))
    toure_renli: Decimal = Field(sa_column=Column("投入人力", Double(asdecimal=True)))
    toure_gongshi_h: Decimal = Field(sa_column=Column("投入工时", Double(asdecimal=True)))
    zhengban_gongshi: Decimal = Field(sa_column=Column("正班工时", Double(asdecimal=True)))
    jiaban_gongshi: Decimal = Field(sa_column=Column("加班工时", Double(asdecimal=True)))
    yichang_gongshi: Decimal = Field(sa_column=Column("异常工时", Double(asdecimal=True)))
    yichang_yuanyin: str = Field(sa_column=Column("异常原因", Text))
    jihuashu: Decimal = Field(sa_column=Column("计划数", Double(asdecimal=True)))
    shiji_chaneng: int = Field(sa_column=Column("实际产能", BigInteger))
    renjun_shiji_chaneng: Decimal = Field(sa_column=Column("人均实际产能", Double(asdecimal=True)))
    biaozhun_chaneng: Decimal = Field(sa_column=Column("标准产能", Double(asdecimal=True)))
    chaneng_dachenglv: Decimal = Field(sa_column=Column("产能达成率", Double(asdecimal=True)))
    buliangshu: Decimal = Field(sa_column=Column("不良数", Double(asdecimal=True)))
    bulianglv: Decimal = Field(sa_column=Column("不良率", Double(asdecimal=True)))
    beizhu: Optional[str] = Field(default=None, sa_column=Column("备注", Text, nullable=True))
    shebei_baoyang_h: Decimal = Field(sa_column=Column("设备保养(H)", Double(asdecimal=True)))
    moju_baoyang_h: Decimal = Field(sa_column=Column("模具保养(H)", Double(asdecimal=True)))
    moju_weixiu_h: Decimal = Field(sa_column=Column("模具维修(H)", Double(asdecimal=True)))
    heidian: Decimal = Field(sa_column=Column("黑点", Double(asdecimal=True)))
    shaojiao: Decimal = Field(sa_column=Column("烧焦", Double(asdecimal=True)))
    bianxing: Decimal = Field(sa_column=Column("变形", Double(asdecimal=True)))
    yiwu: Decimal = Field(sa_column=Column("异物", Double(asdecimal=True)))
    yise: Decimal = Field(sa_column=Column("异色", Double(asdecimal=True)))
    guashang: Decimal = Field(sa_column=Column("刮伤", Double(asdecimal=True)))
    liuhen: Decimal = Field(sa_column=Column("流痕", Double(asdecimal=True)))
    quejiao: Decimal = Field(sa_column=Column("缺胶", Double(asdecimal=True)))
    duojiao: Decimal = Field(sa_column=Column("多胶", Double(asdecimal=True)))
    qipao: Decimal = Field(sa_column=Column("气泡", Double(asdecimal=True)))
    weiyi: Decimal = Field(sa_column=Column("移位", Double(asdecimal=True)))
    yashang: Decimal = Field(sa_column=Column("压伤", Double(asdecimal=True)))
    loutie: Decimal = Field(sa_column=Column("漏铁", Double(asdecimal=True)))
    pifeng: Decimal = Field(sa_column=Column("批锋", Double(asdecimal=True)))
    zangwu: Decimal = Field(sa_column=Column("脏污", Double(asdecimal=True)))
    fahuang: Decimal = Field(sa_column=Column("发黄", Double(asdecimal=True)))
    suoshui: Decimal = Field(sa_column=Column("缩水", Double(asdecimal=True)))
    liaohua: Decimal = Field(sa_column=Column("料花", Double(asdecimal=True)))
    fabai: Decimal = Field(sa_column=Column("发白", Double(asdecimal=True)))
    liangyin: Decimal = Field(sa_column=Column("亮印", Double(asdecimal=True)))
    kunqi: Decimal = Field(sa_column=Column("困气", Double(asdecimal=True)))
    shuiyin: Decimal = Field(sa_column=Column("水印", Double(asdecimal=True)))
    lashang: Decimal = Field(sa_column=Column("拉伤", Double(asdecimal=True)))
    youyin: Decimal = Field(sa_column=Column("油印", Double(asdecimal=True)))
    wudenghong: Decimal = Field(sa_column=Column("无灯孔", Double(asdecimal=True)))
    luomu_buliang: Decimal = Field(sa_column=Column("螺母不良", Double(asdecimal=True)))
    tiaoji_buliang: Decimal = Field(sa_column=Column("调机不良", Double(asdecimal=True)))
    songjian_iqc: Decimal = Field(sa_column=Column("送检IQC", Double(asdecimal=True)))

class ShapeScrap(SQLModel, table=True):
    __tablename__ = "shape_scrap"
    kucun_fangxiang: str = Field(sa_column=Column("库存方向", Text))
    danju_leixing: str = Field(sa_column=Column("单据类型", Text))
    danju_zhuangtai: str = Field(sa_column=Column("单据状态", Text))
    danju_bianhao: str = Field(sa_column=Column("单据编号", Text))
    gongdan_bianhao: str = Field(sa_column=Column("工单编号", Text))
    chanpin_bianma: str = Field(sa_column=Column("产品编码", Text))
    chanpin_mingcheng: str = Field(sa_column=Column("产品名称", Text))
    gongdan_leixing: str = Field(sa_column=Column("工单类型", Text))
    chanpin_cunhuo_leibie: str = Field(sa_column=Column("产品存货类别", Text))
    chanpin_xilie: str = Field(sa_column=Column("产品系列", Text))
    xitong_yuanyin: str = Field(sa_column=Column("系统原因", Text))
    shougong_yuanyin: str = Field(sa_column=Column("手工原因", Text))
    baofei_yuanyin_dalei: Decimal = Field(sa_column=Column("报废原因大类", Double(asdecimal=True)))
    riqi: str = Field(sa_column=Column("日期", Text))
    lingliao_bumen: str = Field(sa_column=Column("领料部门", Text))
    bumen: str = Field(sa_column=Column("部门", Text))
    wuliao_bianma: str = Field(sa_column=Column("物料编码", Text))
    wuliao_mingcheng: str = Field(sa_column=Column("物料名称", Text))
    guige_xinghao: str = Field(sa_column=Column("规格型号", Text))
    chanpin_pinlei: Decimal = Field(sa_column=Column("产品品类", Double(asdecimal=True)))
    wuliao_leibie: str = Field(sa_column=Column("物料类别", Text))
    danwei: str = Field(sa_column=Column("单位", Text))
    shifa_shuliang: Decimal = Field(sa_column=Column("实发数量", Double(asdecimal=True)))
    fahuo_cangku: str = Field(sa_column=Column("发货仓库", Text))
    tiaochu_cangku: Decimal = Field(sa_column=Column("调出仓库", Double(asdecimal=True)))

class ShapeStorage(SQLModel, table=True):
    __tablename__ = "shape_storage"
    laiyuan_danju_leixing: str = Field(sa_column=Column("来源单据类型", Text))
    laiyuan_danju_bianhao: str = Field(sa_column=Column("来源单据编号", Text))
    danju_leixing: str = Field(sa_column=Column("单据类型", Text))
    yewu_riqi: date = Field(sa_column=Column("业务日期", Date))
    zhordu: str = Field(sa_column=Column("周度", Text))
    chanpin_bianma: str = Field(sa_column=Column("产品编码", Text))
    chanpin_mingcheng: str = Field(sa_column=Column("产品名称", Text))
    guige_xinghao: Decimal = Field(sa_column=Column("规格型号", Double(asdecimal=True)))
    chanpin_leixing: str = Field(sa_column=Column("产品类型", Text))
    xilie_fenlei: str = Field(sa_column=Column("系列分类", Text))
    wuliao_fenzu: Decimal = Field(sa_column=Column("物料分组", Double(asdecimal=True)))
    cunhuo_leibie: str = Field(sa_column=Column("存货类别", Text))
    shengchan_chejian: str = Field(sa_column=Column("生产车间", Text))
    jiben_danwei: str = Field(sa_column=Column("基本单位", Text))
    shuliang: int = Field(sa_column=Column("数量", BigInteger))
    danjia: Decimal = Field(sa_column=Column("单价", Double(asdecimal=True)))
    jine: Decimal = Field(sa_column=Column("金额", Double(asdecimal=True)))
    cangku: str = Field(sa_column=Column("仓库", Text))
    shengchan_leixing: Decimal = Field(sa_column=Column("生产类型", Double(asdecimal=True)))
    huozhu: Decimal = Field(sa_column=Column("货主", Double(asdecimal=True)))
    gongdan_leixing: str = Field(sa_column=Column("工单类型", Text))
    gongdan_bianhao: str = Field(sa_column=Column("工单编号", Text))
    pinlei: str = Field(sa_column=Column("品类", Text))

class User(SQLModel, table=True):
    __tablename__ = "user"
    id: int = Field(primary_key=True)
    name: str = Field(sa_column=Column("name", String(255)))
    email: str = Field(sa_column=Column("email", String(255)))

class Zz(SQLModel, table=True):
    __tablename__ = "zz"
    riqi: datetime = Field(sa_column=Column("日期", DateTime))
    shengchan_renwu_danhao: str = Field(sa_column=Column("生产任务单号", Text))
    wuliao_bianma: str = Field(sa_column=Column("物料编码", Text))
    wuliao_mingcheng: str = Field(sa_column=Column("物料名称", Text))
    gongxu: str = Field(sa_column=Column("工序", Text))
    zuoye_neirong: str = Field(sa_column=Column("作业内容", Text))
    banbie: str = Field(sa_column=Column("班别", Text))
    xianbie: str = Field(sa_column=Column("线别", Text))
    biaozhun_renli: Decimal = Field(sa_column=Column("标准人力", Double(asdecimal=True)))
    biaozhun_zong_gongshi: Decimal = Field(sa_column=Column("标准总工时", Double(asdecimal=True)))
    biaozhun_chaneng_uph: Decimal = Field(sa_column=Column("标准产能UPH", Double(asdecimal=True)))
    biaozhun_gongshi_upph: Decimal = Field(sa_column=Column("标准工时UPPH", Double(asdecimal=True)))
    biaozhun_chaneng: Decimal = Field(sa_column=Column("标准产能", Double(asdecimal=True)))
    shiji_renli: int = Field(sa_column=Column("实际人力", BigInteger))
    shiji_zong_gongshi: Decimal = Field(sa_column=Column("实际总工时", Double(asdecimal=True)))
    zhengban_gongshi: Decimal = Field(sa_column=Column("正班工时", Double(asdecimal=True)))
    jiaban_gongshi: int = Field(sa_column=Column("加班工时", BigInteger))
    yichang_gongshi_h: int = Field(sa_column=Column("异常工时(H)", BigInteger))
    shiji_chaneng: int = Field(sa_column=Column("实际产能", BigInteger))
    buliangshu: int = Field(sa_column=Column("不良数", BigInteger))
    shiji_upph: Decimal = Field(sa_column=Column("实际UPPH", Double(asdecimal=True)))
    chaneng_dachenglv: Decimal = Field(sa_column=Column("产能达成率", Double(asdecimal=True)))
    xiaolv_dachenglv: Decimal = Field(sa_column=Column("效率达成率", Double(asdecimal=True)))
    bulianglv: Decimal = Field(sa_column=Column("不良率", Double(asdecimal=True)))
    yichang_yuanyin_zeren_bumen: str = Field(sa_column=Column("异常原因、责任部门", Text))
    beizhu: Optional[Decimal] = Field(default=None, sa_column=Column("备注", Double(asdecimal=True), nullable=True))

class ZzExceptionWks(SQLModel, table=True):
    __tablename__ = "zz_exception_wks"
    riqi: date = Field(sa_column=Column("日期", Date))
    zubie: str = Field(sa_column=Column("组别", Text))
    gongdanhao: str = Field(sa_column=Column("工单号", Text))
    jixing_yanse: str = Field(sa_column=Column("机型颜色", Text))
    yichang_shijian_miaoshu: str = Field(sa_column=Column("异常事件描述", Text))
    yichang_shuxing: str = Field(sa_column=Column("异常属性", Text))
    fasheng_shijian: str = Field(sa_column=Column("发生时间", Text))
    jieshu_shijian: str = Field(sa_column=Column("结束时间", Text))
    shichang: int = Field(sa_column=Column("时长", BigInteger))
    renli: int = Field(sa_column=Column("人力", BigInteger))
    zong_gongshi: int = Field(sa_column=Column("总工时", BigInteger))
    zeren_bumen: str = Field(sa_column=Column("责任部门", Text))
    leibie: str = Field(sa_column=Column("类别", Text))

class ZzScrap(SQLModel, table=True):
    __tablename__ = "zz_scrap"
    danju_bianhao: str = Field(sa_column=Column("单据编号", Text))
    chanpin_huozhu: str = Field(sa_column=Column("产品货主", Text))
    chejian: str = Field(sa_column=Column("车间", Text))
    riqi: date = Field(sa_column=Column("日期", Date))
    danju_zhuangtai: str = Field(sa_column=Column("单据状态", Text))
    shouliao_zuzhi: str = Field(sa_column=Column("收料组织", Text))
    shengchan_zuzhi: str = Field(sa_column=Column("生产组织", Text))
    huozhu: str = Field(sa_column=Column("货主", Text))
    wuliao_bianma: str = Field(sa_column=Column("物料编码", Text))
    wuliao_mingcheng: str = Field(sa_column=Column("物料名称", Text))
    danwei: str = Field(sa_column=Column("单位", Text))
    shenqing_shuliang: Decimal = Field(sa_column=Column("申请数量", Double(asdecimal=True)))
    shidui_shuliang: Decimal = Field(sa_column=Column("实退数量", Double(asdecimal=True)))
    tuiliao_leixing: str = Field(sa_column=Column("退料类型", Text))
    tuiliao_yuanyin: str = Field(sa_column=Column("退料原因", Text))
    kucun_zhuangtai: str = Field(sa_column=Column("库存状态", Text))
    beizhu: Optional[str] = Field(default=None, sa_column=Column("备注", Text, nullable=True))
    wuliao_fenzu: str = Field(sa_column=Column("物料分组", Text))
    cankao_chengben: str = Field(sa_column=Column("参考成本", Text))
    cunhuo_leibie: str = Field(sa_column=Column("存货类别", Text))

class ZzStorage(SQLModel, table=True):
    __tablename__ = "zz_storage"
    danju_bianhao: str = Field(sa_column=Column("单据编号", Text))
    riqi: date = Field(sa_column=Column("日期", Date))
    danju_zhuangtai: str = Field(sa_column=Column("单据状态", Text))
    ruku_zuzhi: str = Field(sa_column=Column("入库组织", Text))
    shengchan_zuzhi: str = Field(sa_column=Column("生产组织", Text))
    zong_chengben: str = Field(sa_column=Column("总成本", Text))
    wuliao_bianma: str = Field(sa_column=Column("物料编码", Text))
    wuliao_mingcheng: str = Field(sa_column=Column("物料名称", Text))
    guige_xinghao: str = Field(sa_column=Column("规格型号", Text))
    chanpin_leixing: str = Field(sa_column=Column("产品类型", Text))
    danwei: str = Field(sa_column=Column("单位", Text))
    yingshou_shuliang: Decimal = Field(sa_column=Column("应收数量", Double(asdecimal=True)))
    shishou_shuliang: Decimal = Field(sa_column=Column("实收数量", Double(asdecimal=True)))
    cangku: str = Field(sa_column=Column("仓库", Text))
    kucun_zhuangtai: str = Field(sa_column=Column("库存状态", Text))
    beizhu: Optional[str] = Field(default=None, sa_column=Column("备注", Text, nullable=True))
    cunhuo_leibie: str = Field(sa_column=Column("存货类别", Text))
    gongdan_bianhao: str = Field(sa_column=Column("工单编号", Text))